---
name: Build Nixie Sketch
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: build
        uses: arduino/compile-sketches@v1
        with:
          fqbn: "esp8266:esp8266:d1_mini_clone"

          platforms: |
            - name: "esp8266:esp8266"
              source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json 
          libraries: |
            - name: NTPCLient
            - name: Time
            - name: Timezone
            - name: ESPEssentials
            - name: ElegantOTA
            - name: ESP8266TimerInterrupt 
          sketch-paths: |
            - src/Nixie
        - name: show 
          run: cd src/Nixie && ls -l
