---
name: Build Nixie Sketch
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2.0.0
      
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266 --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json 

      - name: Install Libraries
        run: |
          arduino-cli lib install NTPClient@3.2.1 Time@1.6.1 Timezone@1.2.4 ESPEssentials@2.1.4 ElegantOTA@3.1.3 ESP8266TimerInterrupt@1.6.0
          
      - name: Compile Sketch
        run: arduino-cli compile -e --fqbn esp8266:esp8266:d1_mini_clone --warnings all ./src/Nixie

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nixie Binary
          path: src/Nixie/build/esp8266.esp8266.d1_mini_clone/Nixie.ino.bin


      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: src/Nixie/build/esp8266.esp8266.d1_mini_clone/Nixie.ino.bin
