---
name: Build Nixie Sketch
on:
  push:
    branches:
      - main

permissions:                    # Füge diese Zeile hinzu
  contents: write                # Stellt sicher, dass die Action Schreibberechtigungen für Inhalte hat
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2.0.0
      
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266 --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json 

      - name: Install Libraries
        run: |
          arduino-cli lib install NTPClient@3.2.1 Time@1.6.1 Timezone@1.2.4 ESPEssentials@2.1.4 ElegantOTA@3.1.3 ESP8266TimerInterrupt@1.6.0 ArduinoJson@7.1.0
          
      - name: Compile Sketch
        run: arduino-cli compile -e --fqbn esp8266:esp8266:d1_mini_clone --warnings all ./src/Nixie

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nixie-binary
          path: src/Nixie/build/esp8266.esp8266.d1_mini_clone/Nixie.ino.bin
  
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: nixie-binary
          path: ./  # Where to download the artifact
          
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          body: Automatically generated release ${{ github.run_number }}
          draft: false
          prerelease: false
          artifacts: |
            Nixie.ino.bin  
